"""PostgreSQL storage for the existing hub ledger, with serialized hub writes."""

import contextlib
import re
from pathlib import Path

from .store import SCHEMA, SCHEMA_VERSION

# Separate keys: one for a running dispatcher/migration, one for ledger writes.
RUN_LOCK = 0x434F574F524B01
WRITE_LOCK = 0x434F574F524B02
POSTGRES_SCHEMA = (
    SCHEMA.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    .replace("INTEGER", "BIGINT")
    .replace(" REAL", " DOUBLE PRECISION")
    .replace(f"PRAGMA user_version = {SCHEMA_VERSION};", "")
)


class Row(dict):
    """Keep sqlite Row's named and positional access for the shared SQL callers."""

    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


def row_factory(cursor):
    names = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values, strict=True))


def parameters(query):
    # All queries are application-owned SQL. Preserve quoted '?' literals, and
    # escape SQL percent characters before translating qmark bind placeholders.
    query = query.replace("%", "%%")
    return re.sub(
        r"'(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|\?", lambda m: "%s" if m[0] == "?" else m[0], query
    )


class Connection:
    def __init__(self, raw, driver):
        self.raw, self.driver = raw, driver

    def execute(self, query, values=()):
        try:
            return self.raw.execute(parameters(query), values)
        except self.driver.IntegrityError:
            # PostgreSQL details can contain an entire row, including token hashes.
            error = self.driver.IntegrityError("Database integrity constraint failed")
        except self.driver.Error:
            error = RuntimeError("PostgreSQL operation failed; transaction was not committed")
        # Raise outside the handler: ASGI middleware can re-expose __context__.
        raise error

    def executemany(self, query, values):
        with self.raw.cursor() as cursor:
            try:
                cursor.executemany(parameters(query), values)
            except self.driver.IntegrityError:
                error = self.driver.IntegrityError("Database integrity constraint failed")
            except self.driver.Error:
                error = RuntimeError("PostgreSQL batch failed; transaction was not committed")
            else:
                return
        raise error


class PostgresStore:
    backend = "postgresql"
    first_environment_sql = "(j.spec::jsonb->'environment_ids'->>0)"

    def __init__(self, url, *, initialize=True):
        try:
            import psycopg
        except ImportError:
            raise RuntimeError("Install cowork-hub[postgres] to use PostgreSQL") from None
        if not url.startswith(("postgresql://", "postgres://")):
            raise RuntimeError("PostgreSQL configuration must contain a PostgreSQL connection URL")
        self._url, self._driver = url, psycopg
        self._run_connection = None
        self.integrity_error = psycopg.IntegrityError
        if initialize:
            self.initialize()

    @classmethod
    def from_file(cls, path, **kwargs):
        try:
            url = Path(path).read_text().strip()
        except OSError:
            raise RuntimeError("Cannot read the PostgreSQL connection file") from None
        return cls(url, **kwargs)

    def connect(self):
        try:
            return self._driver.connect(
                self._url,
                autocommit=True,
                row_factory=row_factory,
                connect_timeout=10,
                application_name="cowork-hub",
            )
        except self._driver.Error:
            raise RuntimeError(
                "Cannot connect to PostgreSQL; check the private connection settings"
            ) from None

    @contextlib.contextmanager
    def transaction(self, *, write=True):
        if self._run_connection is not None:
            try:
                # A lost singleton-lock connection must fail closed, never reconnect.
                self._run_connection.execute("SELECT 1")
            except self._driver.Error:
                raise RuntimeError("PostgreSQL hub lease was lost; restart the hub") from None
        with self.connect() as raw:
            try:
                with raw.transaction():
                    db = Connection(raw, self._driver)
                    if write:
                        # READ COMMITTED takes a fresh snapshot after obtaining the
                        # lock: no two hub writers can reserve from the same budget.
                        db.execute("SET TRANSACTION ISOLATION LEVEL READ COMMITTED")
                        db.execute("SELECT pg_advisory_xact_lock(?)", (WRITE_LOCK,))
                    else:
                        db.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY")
                    yield db
            except self._driver.IntegrityError:
                raise self._driver.IntegrityError("Database integrity constraint failed") from None
            except self._driver.Error:
                raise RuntimeError("PostgreSQL transaction failed") from None

    def initialize(self):
        with self.transaction() as db:
            db.execute(
                "CREATE TABLE IF NOT EXISTS hub_schema (id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL)"
            )
            row = db.execute("SELECT version FROM hub_schema WHERE id=1").fetchone()
            if row and row["version"] not in (4, 5, 6, 7, SCHEMA_VERSION):
                raise RuntimeError("Unsupported PostgreSQL hub schema version")
            for statement in POSTGRES_SCHEMA.split(";"):
                if statement.strip():
                    db.execute(statement)
            db.execute(
                "INSERT INTO hub_schema VALUES(1,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version",
                (SCHEMA_VERSION,),
            )

    @contextlib.contextmanager
    def exclusive_run(self):
        """Only one hub dispatcher or importer may own this database at a time."""
        with self.connect() as raw:
            db = Connection(raw, self._driver)
            if not db.execute("SELECT pg_try_advisory_lock(?)", (RUN_LOCK,)).fetchone()[0]:
                raise RuntimeError(
                    "Another hub or migration is already using this PostgreSQL database"
                )
            try:
                self._run_connection = raw
                yield
            finally:
                self._run_connection = None
                with contextlib.suppress(self._driver.Error):
                    raw.execute("SELECT pg_advisory_unlock(%s)", (RUN_LOCK,))
