export const errors: Record<string, string> = {
  UNAUTHENTICATED: "로그인이 만료됐거나 유효하지 않습니다. 다시 로그인하세요.",
  WEB_NOT_CONFIGURED: "관리자가 웹 로그인 설정을 준비하고 있습니다.",
  WEB_AUTH_UNAVAILABLE: "로그인을 확인할 수 없습니다. 잠시 후 다시 시도하거나 관리자에게 문의하세요.",
  HUB_UNAVAILABLE: "허브 응답을 확인하지 못했습니다. 저장·발급을 요청했다면 목록에서 반영 여부를 확인한 뒤 다시 시도하세요.",
  WEB_ACCOUNT_NOT_LINKED: "처음 사용하는 계정 정보를 등록하고 관리자 승인을 받아 주세요.",
  INVALID_REQUEST: "입력한 내용을 확인하세요.",
  NOT_FOUND: "요청한 항목을 찾을 수 없습니다. 입력값이나 목록을 확인하세요.",
  FORBIDDEN: "이 작업을 수행할 권한이 없습니다.",
  FORBIDDEN_NODE: "해당 서버의 사용 권한이 없습니다.",
  ALREADY_ALLOWED: "이미 사용이 허용된 서버입니다. 작업할 컨테이너에서 연결을 등록하세요.",
  ALREADY_EXISTS: "이미 등록된 사용자 또는 계정입니다.",
  ENVIRONMENT_NOT_APPROVED: "환경 등록 검사를 통과하지 못했습니다. 서버 권한·UID/GID·자원 설정을 확인하세요.",
  INVALID_CAPACITY: "컨테이너 자원이 서버에 등록된 한도를 초과합니다. CPU·메모리·GPU 설정을 확인하세요.",
  IDENTITY_MISMATCH: "등록된 UID·GID와 다릅니다. 본인 계정 정보를 확인하세요.",
  UID_ALREADY_ASSIGNED: "다른 사용자가 등록한 UID입니다.",
  IDENTITY_IN_USE: "기존 실행환경의 UID·GID와 다릅니다.",
  REQUEST_PENDING: "이미 검토 대기 중인 등록 요청이 있습니다.",
  REQUEST_REVIEWED: "이미 검토가 완료된 신청입니다. 목록을 새로고침하세요.",
  IDEMPOTENCY_CONFLICT: "이 요청이 다른 내용으로 접수되어 있습니다. 신청 내역을 확인하세요.",
  STALE_SETTINGS: "다른 곳에서 설정이 변경됐습니다. 새로고침한 뒤 다시 저장하세요.",
  RESOURCES_RESERVED: "현재 예약량보다 낮은 예산은 저장할 수 없습니다.",
  INVALID_WEBHOOK: "Discord에서 복사한 올바른 웹훅 URL을 입력하세요.",
  DESTINATION_UNAVAILABLE: "관리자에게 Discord 등록 기능 활성화를 요청하세요.",
  DESTINATION_GUILD_NOT_ALLOWED: "웹훅은 유효하지만 현재 허용되지 않은 Discord 서버의 채널입니다. 관리자에게 해당 서버의 사용 허용을 요청하세요.",
  DESTINATION_MISMATCH: "웹훅의 채널 정보가 등록 내용과 다릅니다. 본인 채널에서 웹훅 URL을 다시 확인하세요.",
  DESTINATION_IN_USE: "다른 사용자에게 연결된 채널입니다. 본인 전용 채널을 사용하세요.",
  DESTINATION_CHECK_FAILED: "웹훅을 확인하지 못했습니다. Discord의 URL과 연결 상태를 확인하세요.",
  DESTINATION_STORE_FAILED: "채널 설정을 저장하지 못했습니다. 관리자에게 문의하세요.",
  INVALID_SSH_COMMAND: "ssh -p 포트 계정@주소 형식으로 입력하세요. 실행 명령이나 추가 옵션은 넣을 수 없습니다.",
}
